name: Build APK & AAB and Send APK to Telegram

on:
  push:
    branches:
      - main  # or your release branch
  workflow_dispatch:  # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload APK Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Send APK to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F document=@build/app/outputs/flutter-apk/app-release.apk \
               -F chat_id=$TELEGRAM_CHAT_ID \
               -F caption="🚀 New APK build of CSI Hymns Book 📱" \
               https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument

